[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | subprojects
)/
'''

[tool.pytest.ini_options]
addopts = "-ra --ignore-glob=*prereqs.py"
# the prereqs tests are long and tedious, and are an auxiliary function of PyGemini
# we test them explicitly with a CI case.
log_cli = 1
log_cli_level = "INFO"
log_cli_format = "%(levelname)s"
