name: ci

on:
  push:
    paths:
    - "**.py"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7' ]
    name: Linux Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: python -m pip install -e .[tests,lint]

    - run: flake8
    - run: mypy . src scripts

    - run: pytest
      env:
        FC: gfortran-9


  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.7' ]
    name: MacOS Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: python -m pip install -e .[tests,lint]

    - run: pytest
      env:
        FC: gfortran-9


  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.7' ]
    name: Windows Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: python -m pip install -e .[tests,lint]

    - run: pytest
